-- Expanded seed list generated from YC Top Companies (yc-oss mirror) +
-- a curated Best Places to Work list. Run through scripts/discover/run.ts
-- which probes Greenhouse/Lever/Ashby endpoints and only keeps slugs with
-- at least one live job at discovery time. Re-run the discovery script
-- to refresh; stale rows here are skipped (with a log) by the scraper.

insert into public.target_companies (user_id, ats_type, slug, name, active) values
  -- Greenhouse (95)
  (null, 'greenhouse', 'airtable', 'Airtable', true),
  (null, 'greenhouse', 'algolia', 'Algolia', true),
  (null, 'greenhouse', 'alloy', 'Alloy', true),
  (null, 'greenhouse', 'amplitude', 'Amplitude', true),
  (null, 'greenhouse', 'anthropic', 'Anthropic', true),
  (null, 'greenhouse', 'apollo', 'Apollo', true),
  (null, 'greenhouse', 'asana', 'Asana', true),
  (null, 'greenhouse', 'betterment', 'Betterment', true),
  (null, 'greenhouse', 'billcom', 'Bill.com', true),
  (null, 'greenhouse', 'bird', 'Bird', true),
  (null, 'greenhouse', 'braze', 'Braze', true),
  (null, 'greenhouse', 'brex', 'Brex', true),
  (null, 'greenhouse', 'calendly', 'Calendly', true),
  (null, 'greenhouse', 'carta', 'Carta', true),
  (null, 'greenhouse', 'check', 'Check', true),
  (null, 'greenhouse', 'checkr', 'Checkr', true),
  (null, 'greenhouse', 'chime', 'Chime', true),
  (null, 'greenhouse', 'circleci', 'CircleCI', true),
  (null, 'greenhouse', 'clickhouse', 'ClickHouse', true),
  (null, 'greenhouse', 'cloudflare', 'Cloudflare', true),
  (null, 'greenhouse', 'cockroachlabs', 'Cockroach Labs', true),
  (null, 'greenhouse', 'cultureamp', 'Culture Amp', true),
  (null, 'greenhouse', 'customerio', 'Customer.io', true),
  (null, 'greenhouse', 'datadog', 'Datadog', true),
  (null, 'greenhouse', 'dbtlabsinc', 'Dbt Labs', true),
  (null, 'greenhouse', 'descript', 'Descript', true),
  (null, 'greenhouse', 'dropbox', 'Dropbox', true),
  (null, 'greenhouse', 'elastic', 'Elastic', true),
  (null, 'greenhouse', 'epicgames', 'Epic Games', true),
  (null, 'greenhouse', 'faire', 'Faire', true),
  (null, 'greenhouse', 'fastly', 'Fastly', true),
  (null, 'greenhouse', 'fireworksai', 'Fireworks AI', true),
  (null, 'greenhouse', 'fivetran', 'Fivetran', true),
  (null, 'greenhouse', 'flexport', 'Flexport', true),
  (null, 'greenhouse', 'ginkgobioworks', 'Ginkgo Bioworks', true),
  (null, 'greenhouse', 'grafanalabs', 'Grafana Labs', true),
  (null, 'greenhouse', 'greenhouse', 'Greenhouse Software', true),
  (null, 'greenhouse', 'groww', 'Groww', true),
  (null, 'greenhouse', 'gusto', 'Gusto', true),
  (null, 'greenhouse', 'heygen', 'HeyGen', true),
  (null, 'greenhouse', 'hightouch', 'Hightouch', true),
  (null, 'greenhouse', 'honeycomb', 'Honeycomb', true),
  (null, 'greenhouse', 'intercom', 'Intercom', true),
  (null, 'greenhouse', 'iterable', 'Iterable', true),
  (null, 'greenhouse', 'jfrog', 'JFrog', true),
  (null, 'greenhouse', 'klaviyo', 'Klaviyo', true),
  (null, 'greenhouse', 'lattice', 'Lattice', true),
  (null, 'greenhouse', 'launchdarkly', 'LaunchDarkly', true),
  (null, 'greenhouse', 'lucidmotors', 'Lucid Motors', true),
  (null, 'greenhouse', 'make', 'Make', true),
  (null, 'greenhouse', 'medium', 'Medium', true),
  (null, 'greenhouse', 'mercury', 'Mercury', true),
  (null, 'greenhouse', 'merge', 'Merge', true),
  (null, 'greenhouse', 'mixpanel', 'Mixpanel', true),
  (null, 'greenhouse', 'momentus', 'Momentus', true),
  (null, 'greenhouse', 'mongodb', 'MongoDB', true),
  (null, 'greenhouse', 'mutiny', 'Mutiny', true),
  (null, 'greenhouse', 'newrelic', 'New Relic', true),
  (null, 'greenhouse', 'nuro', 'Nuro', true),
  (null, 'greenhouse', 'odeko', 'Odeko', true),
  (null, 'greenhouse', 'oklo', 'Oklo', true),
  (null, 'greenhouse', 'okta', 'Okta', true),
  (null, 'greenhouse', 'pagerduty', 'PagerDuty', true),
  (null, 'greenhouse', 'pilothq', 'Pilot', true),
  (null, 'greenhouse', 'pinterest', 'Pinterest', true),
  (null, 'greenhouse', 'planetscale', 'PlanetScale', true),
  (null, 'greenhouse', 'podium81', 'Podium', true),
  (null, 'greenhouse', 'relativity', 'Relativity Space', true),
  (null, 'greenhouse', 'remote', 'Remote', true),
  (null, 'greenhouse', 'roblox', 'Roblox', true),
  (null, 'greenhouse', 'salesloft', 'Salesloft', true),
  (null, 'greenhouse', 'samsara', 'Samsara', true),
  (null, 'greenhouse', 'scaleai', 'Scale AI', true),
  (null, 'greenhouse', 'scopely', 'Niantic', true),
  (null, 'greenhouse', 'shield', 'Shield AI', true),
  (null, 'greenhouse', 'smartasset', 'SmartAsset', true),
  (null, 'greenhouse', 'sofi', 'SoFi', true),
  (null, 'greenhouse', 'sourcegraph91', 'Sourcegraph', true),
  (null, 'greenhouse', 'spacex', 'SpaceX', true),
  (null, 'greenhouse', 'stabilityai', 'Stability AI', true),
  (null, 'greenhouse', 'stackblitz', 'Stackblitz', true),
  (null, 'greenhouse', 'starburst', 'Starburst', true),
  (null, 'greenhouse', 'temporaltechnologies', 'Temporal', true),
  (null, 'greenhouse', 'tines', 'Tines', true),
  (null, 'greenhouse', 'togetherai', 'Together AI', true),
  (null, 'greenhouse', 'twilio', 'Twilio', true),
  (null, 'greenhouse', 'typeform', 'Typeform', true),
  (null, 'greenhouse', 'vardaspace', 'Varda Space', true),
  (null, 'greenhouse', 'vercel', 'Vercel', true),
  (null, 'greenhouse', 'waymo', 'Waymo', true),
  (null, 'greenhouse', 'wayve', 'Wayve', true),
  (null, 'greenhouse', 'weave', 'Weave', true),
  (null, 'greenhouse', 'webflow', 'Webflow', true),
  (null, 'greenhouse', 'zoominfo', 'ZoomInfo', true),
  (null, 'greenhouse', 'zuora', 'Zuora', true),
  -- Lever (8)
  (null, 'lever', 'angellist', 'AngelList', true),
  (null, 'lever', 'meesho', 'Meesho', true),
  (null, 'lever', 'mistral', 'Mistral AI', true),
  (null, 'lever', 'neon', 'Neon', true),
  (null, 'lever', 'plaid', 'Plaid', true),
  (null, 'lever', 'secureframe', 'Secureframe', true),
  (null, 'lever', 'spotify', 'Spotify', true),
  (null, 'lever', 'wealthfront', 'Wealthfront', true),
  -- Ashby (61)
  (null, 'ashby', 'airbyte', 'Airbyte', true),
  (null, 'ashby', 'ashby', 'Ashby', true),
  (null, 'ashby', 'attio', 'Attio', true),
  (null, 'ashby', 'baseten', 'Baseten', true),
  (null, 'ashby', 'benchling', 'Benchling', true),
  (null, 'ashby', 'character', 'Character AI', true),
  (null, 'ashby', 'claylabs', 'Clay', true),
  (null, 'ashby', 'clipboard', 'Clipboard', true),
  (null, 'ashby', 'cohere', 'Cohere', true),
  (null, 'ashby', 'confluent', 'Confluent', true),
  (null, 'ashby', 'deel', 'Deel', true),
  (null, 'ashby', 'docker', 'Docker', true),
  (null, 'ashby', 'drata', 'Drata', true),
  (null, 'ashby', 'elevenlabs', 'ElevenLabs', true),
  (null, 'ashby', 'frontcareers', 'Front', true),
  (null, 'ashby', 'handshake', 'Handshake', true),
  (null, 'ashby', 'harvey', 'Harvey', true),
  (null, 'ashby', 'influxdata', 'InfluxData', true),
  (null, 'ashby', 'kong', 'Kong', true),
  (null, 'ashby', 'langchain', 'LangChain', true),
  (null, 'ashby', 'llamaindex', 'LlamaIndex', true),
  (null, 'ashby', 'mirage', 'Captions', true),
  (null, 'ashby', 'modal', 'Modal', true),
  (null, 'ashby', 'moderntreasury', 'Modern Treasury', true),
  (null, 'ashby', 'montecarlodata', 'Monte Carlo', true),
  (null, 'ashby', 'mural', 'Mural', true),
  (null, 'ashby', 'n8n', 'n8n', true),
  (null, 'ashby', 'nango', 'Nango', true),
  (null, 'ashby', 'newfront', 'Newfront', true),
  (null, 'ashby', 'notable', 'Notable Labs', true),
  (null, 'ashby', 'notion', 'Notion', true),
  (null, 'ashby', 'ona', 'Gitpod', true),
  (null, 'ashby', 'oyster', 'Oyster HR', true),
  (null, 'ashby', 'paddle', 'Paddle', true),
  (null, 'ashby', 'paragon', 'Paragon', true),
  (null, 'ashby', 'patreon', 'Patreon', true),
  (null, 'ashby', 'persona', 'Persona', true),
  (null, 'ashby', 'pinecone', 'Pinecone', true),
  (null, 'ashby', 'prefect', 'Prefect', true),
  (null, 'ashby', 'puzzle.io', 'Puzzle', true),
  (null, 'ashby', 'railway', 'Railway', true),
  (null, 'ashby', 'redis', 'Redis', true),
  (null, 'ashby', 'render', 'Render', true),
  (null, 'ashby', 'replit', 'Replit', true),
  (null, 'ashby', 'runway', 'Runway', true),
  (null, 'ashby', 'rutter', 'Rutter', true),
  (null, 'ashby', 'ScribdInc', 'Scribd', true),
  (null, 'ashby', 'sentry', 'Sentry', true),
  (null, 'ashby', 'skydio', 'Skydio', true),
  (null, 'ashby', 'snowflake', 'Snowflake', true),
  (null, 'ashby', 'substack', 'Substack', true),
  (null, 'ashby', 'suno', 'Suno', true),
  (null, 'ashby', 'supabase', 'Supabase', true),
  (null, 'ashby', 'synthesia', 'Synthesia', true),
  (null, 'ashby', 'unit', 'Unit', true),
  (null, 'ashby', 'vanta', 'Vanta', true),
  (null, 'ashby', 'velocity', 'Velocity Global', true),
  (null, 'ashby', 'weaviate', 'Weaviate', true),
  (null, 'ashby', 'whatnot', 'Whatnot', true),
  (null, 'ashby', 'writer', 'Writer', true),
  (null, 'ashby', 'zapier', 'Zapier', true)
on conflict (user_id, ats_type, slug) do nothing;
